title: "SHADOW SIGNAL"
description: "Where thoughts grow heavy and burdens lift easier..."
# Set these two based on your repo choice:
url: "https://shadowsignal.github.io"
baseurl: "" # if repo is shadowsignal.github.io
# baseurl: "/shadowsignal.io" # if repo is shadowsignal.io

permalink: /:year/:month/:day/:title/
markdown: kramdown
theme: null

plugins:
  - jekyll-paginate

paginate: 5
paginate_path: "/page:num/"

# Expose minimal data for tags page
collections:
  posts:
    output: true
    permalink: /:year/:month/:day/:title/

# Build settings
exclude:
  - README.md
