title: "Java Joe's Version"
description: "Digital cave of thought dumps"
baseurl: ""
url: "" # set this to your GitHub Pages URL later
markdown: kramdown
paginate: 6
paginate_path: "/page:num/"
plugins:
  - jekyll-paginate
